### ISSUE TITLE
Filtering mechanisms?

### ISSUE THREAD

**Issue by ctrlplusb** [ryanflorence/react-lumberjack#1]
This is awesome, so useful!

Do you think it could be extended to provide filters.

I.e.
-  Only debug components below NamedComponent
-  Include NamedComponent(s)
-  Exclude NamedComponent(s)

The first option feels like it would be the most helpful, but I also have a feeling that it's gonna be a tricky one to implement.

**Comment by ryanflorence** [comment]
Seems interesting, I don't think redux logger lets you do anything similar, feel free to hack on a PR and we'll take a look.

**Comment by lucasbento** [comment]
I was just going to open an issue for this.

I'm currently using Material-UI, I was really looking forward to use this package but it is currently kinda impossible to do so:

![image](https://cloud.githubusercontent.com/assets/6207220/17833736/5f6804e8-66fc-11e6-8489-15dc2d69bc82.png)

It keeps flooding my console with Material-UI state/props being passed even on an element hover.

I did really like the project though.
